project 'Educat.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Educat' do

  pod 'lottie-ios'
  
  #Realm data base
  pod 'RealmSwift', '~> 3.17'
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!


  # Pods for Educat

  target 'EducatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EducatUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
